/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.seguridad.Bitacora;
import Controlador.seguridad.UsuarioConectado;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import vista.seguridad.MantenimientoUsuario;
import vista.seguridad.MantenimientoPerfiles;
import vista.seguridad.MantenimientoAplicacion;
import vista.seguridad.MantenimientoBitacora;
import vista.seguridad.AplicacionaUsuarios;
import vista.seguridad.MantenimientoBodega;
import vista.seguridad.MantenimientoCine;



/**
 *
 * @author visitante
 */
public class MdiGeneral extends javax.swing.JFrame {

    /**
     * Creates new form MdiGeneral
     */
    final int APLICACION=99;
    public MdiGeneral() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MdiGeneral.MAXIMIZED_BOTH);
        this.setTitle("Ejemplo Capas");
        //setDefaultCloseOperation(EXIT_ON_CLOSE);
        cerrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuGeneralSeguridad = new javax.swing.JMenu();
        MenuMantenimientos = new javax.swing.JMenu();
        MantenimientoUsuarios = new javax.swing.JMenuItem();
        MantenimientoAplicaciones = new javax.swing.JMenuItem();
        MantenimientoPerfiles = new javax.swing.JMenuItem();
        mnuAsignaciones = new javax.swing.JMenu();
        AsignacionesAplicacionesPerfil = new javax.swing.JMenuItem();
        AsignacionAplicacionesUsuario = new javax.swing.JMenuItem();
        AsignacionPerfilUsuario = new javax.swing.JMenuItem();
        Bitacora = new javax.swing.JMenu();
        ConsultaBitacora = new javax.swing.JMenuItem();
        salirSistema = new javax.swing.JMenuItem();
        MenuGeneralExamen = new javax.swing.JMenu();
        MantenimientoCine = new javax.swing.JMenuItem();
        MenuGeneralExamen1 = new javax.swing.JMenu();
        MantenimientoCine1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuGeneralExamen2 = new javax.swing.JMenu();
        MantenimientoCine2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        MenuGeneralExamen3 = new javax.swing.JMenu();
        MantenimientoCine3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuGeneralExamen4 = new javax.swing.JMenu();
        MantenimientoCine4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        MenuGeneralSeguridad.setText("Seguridad");

        MenuMantenimientos.setText("Mantenimientos");
        MenuMantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMantenimientosActionPerformed(evt);
            }
        });

        MantenimientoUsuarios.setText("Mantenimiento Usuarios");
        MantenimientoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoUsuariosActionPerformed(evt);
            }
        });
        MenuMantenimientos.add(MantenimientoUsuarios);

        MantenimientoAplicaciones.setText("Mantenimiento Aplicaciones");
        MantenimientoAplicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoAplicacionesActionPerformed(evt);
            }
        });
        MenuMantenimientos.add(MantenimientoAplicaciones);

        MantenimientoPerfiles.setText("Mantenimiento Perfiles");
        MantenimientoPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoPerfilesActionPerformed(evt);
            }
        });
        MenuMantenimientos.add(MantenimientoPerfiles);

        MenuGeneralSeguridad.add(MenuMantenimientos);

        mnuAsignaciones.setText("Asignaciones");

        AsignacionesAplicacionesPerfil.setText("Asignacion Aplicaciones a Perfil");
        AsignacionesAplicacionesPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignacionesAplicacionesPerfilActionPerformed(evt);
            }
        });
        mnuAsignaciones.add(AsignacionesAplicacionesPerfil);

        AsignacionAplicacionesUsuario.setText("Asignacion Aplicaciones a Usuario");
        AsignacionAplicacionesUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignacionAplicacionesUsuarioActionPerformed(evt);
            }
        });
        mnuAsignaciones.add(AsignacionAplicacionesUsuario);

        AsignacionPerfilUsuario.setText("Asignacion Perfil a Usuario");
        AsignacionPerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignacionPerfilUsuarioActionPerformed(evt);
            }
        });
        mnuAsignaciones.add(AsignacionPerfilUsuario);

        MenuGeneralSeguridad.add(mnuAsignaciones);

        Bitacora.setText("Bitacora");
        Bitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BitacoraActionPerformed(evt);
            }
        });

        ConsultaBitacora.setText("Consulta Bitacora");
        ConsultaBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaBitacoraActionPerformed(evt);
            }
        });
        Bitacora.add(ConsultaBitacora);

        MenuGeneralSeguridad.add(Bitacora);

        salirSistema.setText("Salir del Sistema");
        salirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirSistemaActionPerformed(evt);
            }
        });
        MenuGeneralSeguridad.add(salirSistema);

        jMenuBar1.add(MenuGeneralSeguridad);

        MenuGeneralExamen.setText("Catalogos");

        MantenimientoCine.setText("Mantenimiento Bodega");
        MantenimientoCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoCineActionPerformed(evt);
            }
        });
        MenuGeneralExamen.add(MantenimientoCine);

        jMenuBar1.add(MenuGeneralExamen);

        MenuGeneralExamen1.setText("Procesos");

        MantenimientoCine1.setText("Mantenimiento Cines");
        MantenimientoCine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoCine1ActionPerformed(evt);
            }
        });
        MenuGeneralExamen1.add(MantenimientoCine1);

        jMenuItem5.setText("jMenuItem4");
        MenuGeneralExamen1.add(jMenuItem5);

        jMenuBar1.add(MenuGeneralExamen1);

        MenuGeneralExamen2.setText("Informes");

        MantenimientoCine2.setText("Mantenimiento Cines");
        MantenimientoCine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoCine2ActionPerformed(evt);
            }
        });
        MenuGeneralExamen2.add(MantenimientoCine2);

        jMenuItem6.setText("jMenuItem4");
        MenuGeneralExamen2.add(jMenuItem6);

        jMenuBar1.add(MenuGeneralExamen2);

        MenuGeneralExamen3.setText("Herramientas");

        MantenimientoCine3.setText("Mantenimiento Cines");
        MantenimientoCine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoCine3ActionPerformed(evt);
            }
        });
        MenuGeneralExamen3.add(MantenimientoCine3);

        jMenuItem7.setText("jMenuItem4");
        MenuGeneralExamen3.add(jMenuItem7);

        jMenuBar1.add(MenuGeneralExamen3);

        MenuGeneralExamen4.setText("Ayudas");

        MantenimientoCine4.setText("Mantenimiento Cines");
        MantenimientoCine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoCine4ActionPerformed(evt);
            }
        });
        MenuGeneralExamen4.add(MantenimientoCine4);

        jMenuItem8.setText("jMenuItem4");
        MenuGeneralExamen4.add(jMenuItem8);

        jMenuBar1.add(MenuGeneralExamen4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cerrar(){
        try 
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() 
            {
                public void windowClosing(WindowEvent e) 
                {
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e) 
        {
            e.printStackTrace();
        }
    }    
    public void confirmarSalida() 
    {
        int valor=JOptionPane.showConfirmDialog(this,"¿Està seguro de cerrar?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if (valor==JOptionPane.YES_OPTION) 
                    {
                        JOptionPane.showMessageDialog(null, "Gracias por su visita, hasta pronto", "Gracias", JOptionPane.INFORMATION_MESSAGE);
                        System.exit(0);
                    }
    }
    
    private void MenuMantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMantenimientosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuMantenimientosActionPerformed

    private void MantenimientoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoUsuariosActionPerformed
        // TODO add your handling code here:
         // Cerrar otros JInternalFrame antes de abrir uno nuevo//MISHEL
for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
    frame.dispose(); // Cierra cada ventana abierta
    }
        MantenimientoUsuario ventana = new MantenimientoUsuario();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_MantenimientoUsuariosActionPerformed

    private void MantenimientoAplicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoAplicacionesActionPerformed
        // TODO add your handling code here:
         // Cerrar otros JInternalFrame antes de abrir uno nuevo//MISHEL
for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
    frame.dispose(); // Cierra cada ventana abierta
}
        MantenimientoAplicacion ventana = new MantenimientoAplicacion();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_MantenimientoAplicacionesActionPerformed

    private void MantenimientoPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoPerfilesActionPerformed
        // TODO add your handling code here:
                 // Cerrar otros JInternalFrame antes de abrir uno nuevo//MISHEL
for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
    frame.dispose(); // Cierra cada ventana abierta
}
       MantenimientoPerfiles ventana = new MantenimientoPerfiles();
       jDesktopPane1.add(ventana);
       Dimension desktopSize = jDesktopPane1.getSize();
       Dimension FrameSize = ventana.getSize();
       ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_MantenimientoPerfilesActionPerformed

    private void BitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BitacoraActionPerformed
        // TODO add your handling code here:
//       MantenimientoBitacora ventana = new MantenimientoBitacora();
//       jDesktopPane1.add(ventana);
//       Dimension desktopSize = jDesktopPane1.getSize();
//       Dimension FrameSize = ventana.getSize();
//       ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_BitacoraActionPerformed

    private void ConsultaBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaBitacoraActionPerformed
        // TODO add your handling code here:
                 // Cerrar otros JInternalFrame antes de abrir uno nuevo//MISHEL
for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
    frame.dispose(); // Cierra cada ventana abierta
}
       MantenimientoBitacora ventana = new MantenimientoBitacora();
       jDesktopPane1.add(ventana);
       Dimension desktopSize = jDesktopPane1.getSize();
       Dimension FrameSize = ventana.getSize();
       ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_ConsultaBitacoraActionPerformed

    private void AsignacionAplicacionesUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignacionAplicacionesUsuarioActionPerformed
        // TODO add your handling code here:
        //       MantenimientoBitacora ventana = new MantenimientoBitacora();
       for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            frame.dispose(); 
       }
       AplicacionaUsuarios ventana = new AplicacionaUsuarios();
       jDesktopPane1.add(ventana);
       Dimension desktopSize = jDesktopPane1.getSize();
       Dimension FrameSize = ventana.getSize();
       ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_AsignacionAplicacionesUsuarioActionPerformed

    private void AsignacionPerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignacionPerfilUsuarioActionPerformed
        // TODO add your handling code here:
        //       MantenimientoBitacora ventana = new MantenimientoBitacora();
//       jDesktopPane1.add(ventana);
//       Dimension desktopSize = jDesktopPane1.getSize();
//       Dimension FrameSize = ventana.getSize();
//       ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        
    }//GEN-LAST:event_AsignacionPerfilUsuarioActionPerformed

    private void AsignacionesAplicacionesPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignacionesAplicacionesPerfilActionPerformed
        // TODO add your handling code here:
        //       MantenimientoBitacora ventana = new MantenimientoBitacora();
//       jDesktopPane1.add(ventana);
//       Dimension desktopSize = jDesktopPane1.getSize();
//       Dimension FrameSize = ventana.getSize();
//       ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_AsignacionesAplicacionesPerfilActionPerformed

    private void salirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirSistemaActionPerformed
        // TODO add your handling code here:
                 // Cerrar otros JInternalFrame antes de abrir uno nuevo//MISHEL
for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
    frame.dispose(); // Cierra cada ventana abierta
}
//        
        int valor=JOptionPane.showConfirmDialog(this,"¿Està seguro de cerrar?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if (valor==JOptionPane.YES_OPTION) 
                    {
                        JOptionPane.showMessageDialog(null, "Gracias por su visita, hasta pronto", "Gracias", JOptionPane.INFORMATION_MESSAGE);
                        System.exit(0);
                    }
    }//GEN-LAST:event_salirSistemaActionPerformed

    private void MantenimientoCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoCineActionPerformed
        // TODO add your handling code here:
        for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
    frame.dispose(); // Cierra cada ventana abierta
}
       MantenimientoBodega ventana = new MantenimientoBodega();
       jDesktopPane1.add(ventana);
       Dimension desktopSize = jDesktopPane1.getSize();
       Dimension FrameSize = ventana.getSize();
       ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_MantenimientoCineActionPerformed

    private void MantenimientoCine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoCine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientoCine1ActionPerformed

    private void MantenimientoCine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoCine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientoCine2ActionPerformed

    private void MantenimientoCine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoCine3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientoCine3ActionPerformed

    private void MantenimientoCine4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoCine4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientoCine4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AsignacionAplicacionesUsuario;
    private javax.swing.JMenuItem AsignacionPerfilUsuario;
    private javax.swing.JMenuItem AsignacionesAplicacionesPerfil;
    private javax.swing.JMenu Bitacora;
    private javax.swing.JMenuItem ConsultaBitacora;
    private javax.swing.JMenuItem MantenimientoAplicaciones;
    private javax.swing.JMenuItem MantenimientoCine;
    private javax.swing.JMenuItem MantenimientoCine1;
    private javax.swing.JMenuItem MantenimientoCine2;
    private javax.swing.JMenuItem MantenimientoCine3;
    private javax.swing.JMenuItem MantenimientoCine4;
    private javax.swing.JMenuItem MantenimientoPerfiles;
    private javax.swing.JMenuItem MantenimientoUsuarios;
    private javax.swing.JMenu MenuGeneralExamen;
    private javax.swing.JMenu MenuGeneralExamen1;
    private javax.swing.JMenu MenuGeneralExamen2;
    private javax.swing.JMenu MenuGeneralExamen3;
    private javax.swing.JMenu MenuGeneralExamen4;
    private javax.swing.JMenu MenuGeneralSeguridad;
    private javax.swing.JMenu MenuMantenimientos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu mnuAsignaciones;
    private javax.swing.JMenuItem salirSistema;
    // End of variables declaration//GEN-END:variables
}
